CREATE TABLE "GCG_3144_MVE_TKT_SU" IN DICTIONARY USING 'GCG_3144_MVE_TKT_SU.mkd' PAGESIZE=4096 (
 "TRMNL" CHAR(3) NOT NULL,
 "COMMENTS" LONGVARCHAR NOT NULL,
 "PRINTER" CHAR(100),
 "SCRAPPRINTER" CHAR(100) );
